#!/bin/bash

gcc -S -masm=intel $CFILE   |Expl: gcc -S -masm=intel 'variable name'&|C file name will be saved in the 'variable_name' & output main.s 



8

#include <stdio.h>

#include <stdlib.h>



/**

 * main - Entry point

 * Return: Always 1 (Success)

 */

int main(void)

{

 write(STDOUT_FILENO, "and that piece of art is useful

   \" - Dora Korpar, 2015-10-19\n", 59);

 return (1);

}
